name: Generated AAB

env:
  main_project_module: app

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Make Gradle executable
        run: |
          tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
          chmod +x ./gradlew

      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/

      - name: Locate AAB file
        id: find_aab
        shell: bash
        run: |
          AAB=$(ls ${{ env.main_project_module }}/build/outputs/bundle/release/*.aab | head -n 1)
          if [ -z "$AAB" ]; then
            echo "No AAB found"; exit 1
          fi
          echo "AAB_PATH=$AAB" >> $GITHUB_ENV
          echo "aab_path=$AAB" >> $GITHUB_OUTPUT

      - name: Extract version from libs.versions.toml
        id: extract_version
        shell: bash
        run: |
          VERSION="$(grep -E '^versionName\s*=' gradle/libs.versions.toml \
            | sed -E 's/.* = \s*"([^"]+)".*/\1/')"

          if [ -z "$VERSION" ]; then
            echo "❌ versionName not found"
            exit 1
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and push git tag
        run: |
          TAG="${{ env.VERSION }}"

          if git ls-remote --tags origin | grep -q "refs/tags/$TAG$"; then
            echo "❌ Remote tag $TAG already exists"
            exit 1
          fi

          git tag "$TAG"
          git push origin "$TAG"


      - name: Create GitHub Release and upload AAB
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            ${{ env.AAB_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
